name: C/C++ CI

on:
  push:
    branches: [ "master", "feature/**", "fix/**" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: build and run tests
      run: |
        make CXXFLAGS="-std=c++14" test
        make CXXFLAGS="-std=c++14" test_cdc
        make CXXFLAGS="-std=c++14" test_uac1
    - name: run tests
      run: |
        ./test
        ./test_cdc
        ./test_uac1
